//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using CoCoME.Terminal.Contracts;
using System.Linq;
using Tecan.Sila2;
using Tecan.Sila2.Client;
using Tecan.Sila2.Server;

namespace CoCoME.Terminal.CashboxService
{
    
    
    ///  <summary>
    /// A class that exposes the ICashboxService interface via SiLA2
    /// </summary>
    [System.ComponentModel.Composition.ExportAttribute(typeof(IFeatureProvider))]
    [System.ComponentModel.Composition.PartCreationPolicyAttribute(System.ComponentModel.Composition.CreationPolicy.Shared)]
    public partial class CashboxServiceProvider : IFeatureProvider
    {
        
        private ICashboxService _implementation;
        
        private Tecan.Sila2.Server.ISiLAServer _server;
        
        private static Tecan.Sila2.Feature _feature = FeatureSerializer.LoadFromAssembly(typeof(CashboxServiceProvider).Assembly, "CashboxService.sila.xml");
        
        ///  <summary>
        /// Creates a new instance
        /// </summary>
        /// <param name="implementation">The implementation to exported through SiLA2</param>
        /// <param name="server">The SiLA2 server instance through which the implementation shall be exported</param>
        [System.ComponentModel.Composition.ImportingConstructorAttribute()]
        public CashboxServiceProvider(ICashboxService implementation, Tecan.Sila2.Server.ISiLAServer server)
        {
            _implementation = implementation;
            _server = server;
        }
        
        ///  <summary>
        /// The feature that is exposed by this feature provider
        /// </summary>
        /// <returns>A feature object</returns>
        public Tecan.Sila2.Feature FeatureDefinition
        {
            get
            {
                return _feature;
            }
        }
        
        ///  <summary>
        /// Registers the feature in the provided feature registration
        /// </summary>
        /// <param name="registration">The registration component to which the feature should be registered</param>
        public void Register(IServerBuilder registration)
        {
            registration.RegisterCommandWithIntermediates<ListenToCashdeskButtonsRequestDto, CashboxButton, ListenToCashdeskButtonsIntermediateDto>("ListenToCashdeskButtons", ListenToCashdeskButtons, ConvertListenToCashdeskButtonsIntermediate, null);
        }
        
        private ListenToCashdeskButtonsIntermediateDto ConvertListenToCashdeskButtonsIntermediate(CashboxButton intermediate)
        {
            return new ListenToCashdeskButtonsIntermediateDto(intermediate, _server);
        }
        
        ///  <summary>
        /// Executes the Listen To Cashdesk Buttons command
        /// </summary>
        /// <param name="request">A data transfer object that contains the command parameters</param>
        /// <returns>The command response wrapped in a data transfer object</returns>
        protected virtual Tecan.Sila2.IIntermediateObservableCommand<CashboxButton> ListenToCashdeskButtons(ListenToCashdeskButtonsRequestDto request)
        {
            return new ObservableRxCommand<CoCoME.Terminal.Contracts.CashboxButton>(_implementation.ListenToCashdeskButtons());
        }
        
        ///  <summary>
        /// Gets the command with the given identifier
        /// </summary>
        /// <param name="commandIdentifier">A fully qualified command identifier</param>
        /// <returns>A method object or null, if the command is not supported</returns>
        public System.Reflection.MethodInfo GetCommand(string commandIdentifier)
        {
            if ((commandIdentifier == "cocome.terminal/contracts/CashboxService/v1/Command/ListenToCashdeskButtons"))
            {
                return typeof(ICashboxService).GetMethod("ListenToCashdeskButtons");
            }
            return null;
        }
        
        ///  <summary>
        /// Gets the property with the given identifier
        /// </summary>
        /// <param name="propertyIdentifier">A fully qualified property identifier</param>
        /// <returns>A property object or null, if the property is not supported</returns>
        public System.Reflection.PropertyInfo GetProperty(string propertyIdentifier)
        {
            return null;
        }
    }
}


