//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using BankServer.Contracts;
using System.Linq;
using Tecan.Sila2;
using Tecan.Sila2.Client;
using Tecan.Sila2.Server;

namespace BankServer.BankServer
{
    
    
    ///  <summary>
    /// A class that exposes the IBankServer interface via SiLA2
    /// </summary>
    [System.ComponentModel.Composition.ExportAttribute(typeof(IFeatureProvider))]
    [System.ComponentModel.Composition.PartCreationPolicyAttribute(System.ComponentModel.Composition.CreationPolicy.Shared)]
    public partial class BankServerProvider : IFeatureProvider
    {
        
        private IBankServer _implementation;
        
        private Tecan.Sila2.Server.ISiLAServer _server;
        
        private static Tecan.Sila2.Feature _feature = FeatureSerializer.LoadFromAssembly(typeof(BankServerProvider).Assembly, "BankServer.sila.xml");
        
        ///  <summary>
        /// Creates a new instance
        /// </summary>
        /// <param name="implementation">The implementation to exported through SiLA2</param>
        /// <param name="server">The SiLA2 server instance through which the implementation shall be exported</param>
        [System.ComponentModel.Composition.ImportingConstructorAttribute()]
        public BankServerProvider(IBankServer implementation, Tecan.Sila2.Server.ISiLAServer server)
        {
            _implementation = implementation;
            _server = server;
        }
        
        ///  <summary>
        /// The feature that is exposed by this feature provider
        /// </summary>
        /// <returns>A feature object</returns>
        public Tecan.Sila2.Feature FeatureDefinition
        {
            get
            {
                return _feature;
            }
        }
        
        ///  <summary>
        /// Registers the feature in the provided feature registration
        /// </summary>
        /// <param name="registration">The registration component to which the feature should be registered</param>
        public void Register(IServerBuilder registration)
        {
            registration.RegisterUnobservableCommand<CreateContextRequestDto, CreateContextResponseDto>("CreateContext", CreateContext);
            registration.RegisterUnobservableCommand<AuthorizePaymentRequestDto, EmptyRequest>("AuthorizePayment", AuthorizePayment);
        }
        
        ///  <summary>
        /// Executes the Create Context command
        /// </summary>
        /// <param name="request">A data transfer object that contains the command parameters</param>
        /// <returns>The command response wrapped in a data transfer object</returns>
        protected virtual CreateContextResponseDto CreateContext(CreateContextRequestDto request)
        {
            try
            {
                return new CreateContextResponseDto(_implementation.CreateContext(((int)(request.Amount.Extract(_server)))), _server);
            } catch (System.ArgumentException ex)
            {
                if ((ex.ParamName == "amount"))
                {
                    throw _server.ErrorHandling.CreateValidationError("com.mybank/banking/BankServer/v1/Command/CreateContext/Parameter/Amount", ex.Message);
                }
                throw _server.ErrorHandling.CreateUnknownValidationError(ex);
            }
        }
        
        ///  <summary>
        /// Executes the Authorize Payment command
        /// </summary>
        /// <param name="request">A data transfer object that contains the command parameters</param>
        /// <returns>The command response wrapped in a data transfer object</returns>
        protected virtual EmptyRequest AuthorizePayment(AuthorizePaymentRequestDto request)
        {
            try
            {
                _implementation.AuthorizePayment(request.TransactionContextId.Extract(_server), request.Account.Extract(_server), request.AuthorizationToken.Extract(_server));
                return EmptyRequest.Instance;
            } catch (System.ArgumentException ex)
            {
                if ((ex.ParamName == "transactionContextId"))
                {
                    throw _server.ErrorHandling.CreateValidationError("com.mybank/banking/BankServer/v1/Command/AuthorizePayment/Parameter/TransactionCo" +
                            "ntextId", ex.Message);
                }
                if ((ex.ParamName == "account"))
                {
                    throw _server.ErrorHandling.CreateValidationError("com.mybank/banking/BankServer/v1/Command/AuthorizePayment/Parameter/Account", ex.Message);
                }
                if ((ex.ParamName == "authorizationToken"))
                {
                    throw _server.ErrorHandling.CreateValidationError("com.mybank/banking/BankServer/v1/Command/AuthorizePayment/Parameter/Authorization" +
                            "Token", ex.Message);
                }
                throw _server.ErrorHandling.CreateUnknownValidationError(ex);
            }
        }
        
        ///  <summary>
        /// Gets the command with the given identifier
        /// </summary>
        /// <param name="commandIdentifier">A fully qualified command identifier</param>
        /// <returns>A method object or null, if the command is not supported</returns>
        public System.Reflection.MethodInfo GetCommand(string commandIdentifier)
        {
            if ((commandIdentifier == "com.mybank/banking/BankServer/v1/Command/CreateContext"))
            {
                return typeof(IBankServer).GetMethod("CreateContext");
            }
            if ((commandIdentifier == "com.mybank/banking/BankServer/v1/Command/AuthorizePayment"))
            {
                return typeof(IBankServer).GetMethod("AuthorizePayment");
            }
            return null;
        }
        
        ///  <summary>
        /// Gets the property with the given identifier
        /// </summary>
        /// <param name="propertyIdentifier">A fully qualified property identifier</param>
        /// <returns>A property object or null, if the property is not supported</returns>
        public System.Reflection.PropertyInfo GetProperty(string propertyIdentifier)
        {
            return null;
        }
    }
}


